### PR TITLE
Add missing include for integer types (needed for GCC 13)

### PR DESCRIPTION
**Pull request by DailyMats**
The current master does not build on Ubuntu 23.10:

```
root@df7042aa9f8f:/uap-cpp# make
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 UaParser.cpp -o UaParser.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/Pattern.cpp -o internal/Pattern.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/AlternativeExpander.cpp -o internal/AlternativeExpander.o
g++ -c  -std=c++0x -Wall -Werror -g -fPIC -O3 internal/SnippetIndex.cpp -o internal/SnippetIndex.o
In file included from internal/SnippetIndex.cpp:1:
internal/SnippetIndex.h:22:11: error: 'uint32_t' does not name a type
   22 |   typedef uint32_t SnippetId;
      |           ^~~~~~~~
internal/SnippetIndex.h:9:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    8 | #include <vector>
  +++ |+#include <cstdint>
    9 |
```

This PR adds the missing includes.

### CODE REVIEW

**Comment by prm-james-hill** [comment]
Hitting the same issue. Not sure who has write access to this repo. @asuhan ?

**Comment by asuhan** [comment]
Thanks!
